# Generated by Django 5.0.7 on 2024-08-01 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstatus',
            options={'verbose_name_plural': 'User status '},
        ),
    ]
