# Generated by Django 5.0.7 on 2024-08-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_custom_auth', '0002_alter_userstatus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profile_pic',
            new_name='profile_picture',
        ),
    ]
